name: Build and Package TodoList

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Download JavaFX SDK and JMODs
        run: |
          curl -L https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_osx-x64_bin-sdk.zip -o javafx.zip
          unzip javafx.zip -d javafx
          curl -L https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_osx-x64_bin-jmods.zip -o jmods.zip
          unzip jmods.zip -d javafx-jmods

      - name: Clean previous builds
        run: |
          rm -rf dist/mac
          rm -rf runtime-mac

      - name: Build project
        run: mvn clean package

      - name: Package macOS app
        run: |
          jlink \
            --module-path $JAVA_HOME/jmods:javafx-jmods/javafx-jmods-24.0.1 \
            --add-modules java.base,javafx.controls,javafx.fxml \
            --output runtime-mac \
            --strip-debug --compress=2 --no-header-files --no-man-pages

          jpackage \
            --type app-image \
            --input target \
            --dest dist/mac \
            --name TodoList \
            --main-jar todolist-1.0-SNAPSHOT-jar-with-dependencies.jar \
            --main-class com.todo.javiergrande.Main \
            --runtime-image runtime-mac \
            --icon src/main/resources/icon.icns

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: TodoList-mac
          path: dist/mac/TodoList.app

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Download JavaFX SDK and JMODs
        run: |
          Invoke-WebRequest -Uri https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_windows-x64_bin-sdk.zip -OutFile javafx.zip
          Expand-Archive javafx.zip -DestinationPath javafx
          Invoke-WebRequest -Uri https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_windows-x64_bin-jmods.zip -OutFile jmods.zip
          Expand-Archive jmods.zip -DestinationPath javafx-jmods

      - name: Clean previous builds
        run: |
          Remove-Item -Recurse -Force dist\win,runtime-win

      - name: Build project
        run: mvn clean package

      - name: Package Windows app
        run: |
          jlink `
            --module-path "$Env:JAVA_HOME\jmods;javafx-jmods\javafx-jmods-24.0.1" `
            --add-modules java.base,javafx.controls,javafx.fxml `
            --output runtime-win `
            --strip-debug --compress=2 --no-header-files --no-man-pages

          jpackage `
            --type exe `
            --input target `
            --dest dist\win `
            --name TodoList `
            --main-jar todolist-1.0-SNAPSHOT-jar-with-dependencies.jar `
            --main-class com.todo.javiergrande.Main `
            --runtime-image runtime-win `
            --icon src\main\resources\icon.ico

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: TodoList-windows
          path: dist/win/TodoList.exe

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Download JavaFX SDK and JMODs
        run: |
          curl -L https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_linux-x64_bin-sdk.zip -o javafx.zip
          unzip javafx.zip -d javafx
          curl -L https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_linux-x64_bin-jmods.zip -o jmods.zip
          unzip jmods.zip -d javafx-jmods

      - name: Clean previous builds
        run: |
          rm -rf dist/linux
          rm -rf runtime-linux

      - name: Build project
        run: mvn clean package

      - name: Package Linux app
        run: |
          jlink \
            --module-path $JAVA_HOME/jmods:javafx-jmods/javafx-jmods-24.0.1 \
            --add-modules java.base,javafx.controls,javafx.fxml \
            --output runtime-linux \
            --strip-debug --compress=2 --no-header-files --no-man-pages

          jpackage \
            --type app-image \
            --input target \
            --dest dist/linux \
            --name TodoList \
            --main-jar todolist-1.0-SNAPSHOT-jar-with-dependencies.jar \
            --main-class com.todo.javiergrande.Main \
            --runtime-image runtime-linux \
            --icon src/main/resources/icon.png

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: TodoList-linux
          path: dist/linux/TodoList

  release:
    name: Publish GitHub Release
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Display files
        run: ls -R dist

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/TodoList-windows/TodoList.exe
            dist/TodoList-mac/TodoList.app/**/* 
            dist/TodoList-linux/TodoList/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}